language: csharp
solution: Rockyfi.sln
install:
  - nuget restore Rockyfi/Rockyfi.sln
  - nuget restore RockyfiTests/RockyfiTests.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Rockyfi/Rockyfi.sln
  - msbuild /p:Configuration=Release RockyfiTests/RockyfiTests.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./RockyfiTests/bin/Release/RockyfiTests.dll